version: "3.9"  # optional since v1.27.0
services:
  node-docker-app:
    build: .
    ports:
      - "8642:8642"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=8642
    # env_file:
    #   - ./.env